source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.4.0"

gem "bootsnap", ">= 1.1.0", require: false
gem "jbuilder", "~> 2.5"
gem "pg"
gem "puma", "~> 3.11"
gem "rails", "~> 5.2.0"
gem "uglifier", ">= 1.3.0"
gem "dotenv-rails"
gem "config"
gem "httparty"

group :development, :test do
  gem "pry", require: false
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"
end

group :test do
  gem "factory_bot"
  gem "rspec-rails"
  gem "shoulda-matchers"
  gem "webmock"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
